<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Dekode\\GravityForms\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Dekode\\GravityForms\\Vendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Dekode\\GravityForms\\Vendor\\NeutronStandard\\' => array($vendorDir . '/automattic/phpcs-neutron-standard/NeutronStandard'),
    'Dekode\\GravityForms\\Vendor\\MicrosoftAzure\\Storage\\File\\' => array($vendorDir . '/microsoft/azure-storage-file/src/File'),
    'Dekode\\GravityForms\\Vendor\\MicrosoftAzure\\Storage\\Common\\' => array($vendorDir . '/microsoft/azure-storage-common/src/Common'),
    'Dekode\\GravityForms\\Vendor\\MicrosoftAzure\\Storage\\Blob\\' => array($vendorDir . '/microsoft/azure-storage-blob/src/Blob'),
    'Dekode\\GravityForms\\Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Dekode\\GravityForms\\Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Dekode\\GravityForms\\Vendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Dekode\\GravityForms\\Vendor\\Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => array($vendorDir . '/dealerdirect/phpcodesniffer-composer-installer/src'),
);
